### ISSUE TITLE
Numeros de ficha atraviesan otras fichas

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#10]
### Comportamiento esperado
Las números de valor de la ficha no deben atravesar a las otras fichas. El numero de valor en la ficha solo van en los marcos.

### Comportamiento real
El valor en las fichas de bonificación atraviesan a las otras fichas. Las fichas de mercancía desde plata hasta la ultima muestran un número en el medio.

### Pasos a reproducir
1. Inicie la partida.
2. Note como los valores en las fichas de bonificación atraviesan a las fichas.
3. Note como las fichas de mercancía desde plata hasta la ultima muestran un número en medio.

**Comment by davidrochin** [comment]
Este Issue se solucionó con el commit d5a0f4276e860ee5ef3018108a4097d298fc3657.
