### ISSUE TITLE
La mitad del mazo principal no se barajea correctamente

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#12]
### Comportamiento esperado
Que todas las cartas del mazo estén barajeadas correctamente.

### Comportamiento real
La mitad de cartas están barajeadas mientras el resto siguen sin barajearse.

### Pasos a reproducir
1.-Iniciar partida
2.-Jugar la partida normalmente hasta acabarse la mitad de las cartas.
3.-Note que las siguientes cartas no están barajeadas.

**Comment by davidrochin** [comment]
Cerrado. Solucionado con el commit 808f068.
