### ISSUE TITLE
Ronda se acaba antes de que se acaben 3 tipos de fichas de mercancía

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#13]
### Comportamiento esperado
Que cuando se acaben 3 pilas de fichas de tipo producto o se acabe el mazo de robo se acabe la ronda.

### Comportamiento real
Si se acaban 2 pilas de fichas de tipo producto y una pila de ficha bonificación se acaba la ronda.

### Pasos a reproducir
1-Inicie la partida.
2.-Venda mercancía hasta acabar con una pila de fichas de bonificación.
3.-Venda hasta acabar dos pila de fichas producto.
4.-Note como se acaba la ronda.

**Comment by davidrochin** [comment]
Issue cerrado. Se solucionó con el commit 808f068.
