### ISSUE TITLE
Texto al finalizar la partida

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#14]
### Comportamiento esperado
Al finalizar la partida solo muestre el mensaje si gané o perdí.

### Comportamiento real
Se muestra en la esquina superior izquierda un mensaje que dice "iniciar prueba" por menos de un segundo.

### Pasos a reproducir
1. Iniciar una partida
2. Ganar 2 rondas para finalizar partida.
3. Darle en clic en el botón cuando diga quien ganó.

**Comment by davidrochin** [comment]
Resuelto en el commit d99ebc3. Issue cerrado.
