### ISSUE TITLE
Ortografía en los mensajes durante la partida

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#15]
### Comportamiento esperado
Que los mensajes siguientes estén escritos correctamente:
-"No puedes recibir más cartas de las que ofreces."
-"No puedes tomar más de una carta, al menos que sean camellos."
-"Tu oponente ha tomado una carta de tipo (tipo de carta)."

### Comportamiento real
Los mensajes dicen lo siguiente:
-"No puedes recibir mas cartas de las que ofreces."
-"No puedes tomar mas de una carta, al menos sean camellos."
-"Tu oponente ha tomado una carta de tipo (tipo de carta)"

### Pasos para reproducir
1. Iniciar una ronda.
2. Intentar hacer un trueque ofreciendo menos cartas de las que se ofrece.
3. Intentar tomar 2 o más cartas del mercado.
4. Tomar una carta del mercado y ver la el mensaje que aparece en el oponente.

**Comment by davidrochin** [comment]
Issue cerrado. Errores ortográficos fueron corregidos en el commit bdf5a16.
