### ISSUE TITLE
El jugador puede vender aunque no haya fichas de mercancía

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#16]
### Comportamiento esperado
El jugador no debe poder vender fichas de mercancía si ya no hay fichas de tipo mercancía para tomar.

### Comportamiento real
El jugador puede vender fichas de mercancía aun sin haber fichas de esa mercancía para tomar.

### Pasos a reproducir
1. Iniciar una partida.
2. Vender 7 fichas en el caso de telas y especias, 9 en el caso de cuero. 
3. Vender la ficha restante de cualquiera de las mercancías mencionadas.
4. Note como se realizó la venta.

**Comment by davidrochin** [comment]
El manual dice "En algunas ocasiones, hay menos fichas disponibles que cartas durante una venta. En este caso, se sigue recibiendo la ficha de bonificación por el numero de cartas vendidas.", por lo tanto, el comportamiento actual del juego es correcto.
