### ISSUE TITLE
El contador de rupias solo puede mostrar números de 2 cifras

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#17]
### Comportamiento esperado
Que se muestre el total de puntos que lleva el jugador.

### Comportamiento real
Si el jugador pasa de 100 puntos, solo se muestran las ultimas 2 cifras.

### Pasos a reproducir
1. Iniciar la partida.
2. Vender fichas de mercancía hasta que se llegue a 100 puntos o más.

**Comment by davidrochin** [comment]
Solucionado en el commit f5a4441. Issue cerrado.
