### ISSUE TITLE
Se pueden vender las cartas mas caras desde una unidad

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#4]
### Comportamiento esperado
Las cartas de mercancía más cara (diamante, oro y plata) solo se pueden vender mínimo 2.

### Comportamiento real
Se pueden vender las cartas mercancía desde una unidad.

### Pasos a reproducir
1. Iniciar partida.
2. Seleccionar una carta de la mercancía mas cara del mazo del jugador.
3. Intente vender.
4. Note que si selecciona una sola carta le permite vender

**Comment by davidrochin** [comment]
Este Issue se solucionó con el commit ede60eb9c4601bd4e7092abb58814a5d25410569.
