### ISSUE TITLE
No se muestra la dirección IP del anfitrión

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#5]
### Comportamiento esperado
Se quiere que se muestre la dirección IP del anfitrión para compartirla al otro jugador.

### Comportamiento real
No se muestra la dirección IP del anfitrión se tiene que buscar por medio de comando en CMD.

### Pasos a reproducir
1. Crear partida
2. Note que no te sale la dirección IP de anfitrión.

**Comment by davidrochin** [comment]
Este Issue ha sido resuelto en el commit a7e9c21e3d368dbe61a494c88a860b326e9273f5.
