### ISSUE TITLE
Textura de fichas de camello incorrecta

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#8]
### Comportamiento esperado
La textura que tiene la ficha camello sea la correcta.

### Comportamiento real
La textura que tiene la ficha camello es la incorrecta.

### Pasos a reproducir
1. Inicie la partida.
2. Note que la textura de la ficha camello es la incorrecta.

**Comment by davidrochin** [comment]
Este Issue se resolvió con el commit d5a0f4276e860ee5ef3018108a4097d298fc3657.
