### ISSUE TITLE
Inicio de turno

### ISSUE THREAD

**Issue by christianLugo5** [jdrc8/Jaipur-3D#9]
### Comportamiento esperado
Al inicio de la partida el primer turno debe ser aleatorio.

### Comportamiento real
El anfitrión siempre tiene el primer turno en la primer ronda.

### Pasos a reproducir
1. Inicie la partida como anfitrión.
2. Note que siempre tiene el primer el turno.

**Comment by davidrochin** [comment]
Este Issue fue solucionado con el commit 9580a8c619f1f2cd3a27954865cecbe9b696bd1a.
